// Every user-facing string in one place. Written fresh for Mysl; replica-brand rewrites these in the brand voice.
export const t = {
  product: "Мысль",
  login: {
    title: "Вход в Мысль",
    lead: "Доска, на которой думают вместе.",
    name: "Как вас зовут",
    email: "Электронная почта",
    submit: "Войти",
    devNote: "Тестовый вход: пароль пока не нужен.",
    errorEmail: "Проверьте адрес почты",
  },
  dash: {
    title: "Мои доски",
    newBoard: "Новая доска",
    search: "Найти доску",
    sortOpened: "Недавно открытые",
    sortModified: "Недавно изменённые",
    sortName: "По названию",
    all: "Все",
    starred: "Избранные",
    trash: "Корзина",
    emptyTitle: "Здесь пока пусто",
    emptyBody: "Создайте первую доску: это одна кнопка.",
    emptySearch: (q: string) => `По запросу «${q}» досок нет`,
    emptyStarred: "Отметьте доску звёздочкой, и она появится здесь.",
    emptyTrash: "Корзина пуста. Удалённые доски хранятся здесь 30 дней.",
    open: "Открыть",
    rename: "Переименовать",
    star: "В избранное",
    unstar: "Убрать из избранного",
    delete: "В корзину",
    restore: "Восстановить",
    edited: "Изменена",
    signOut: "Выйти",
  },
  board: {
    back: "Все доски",
    untitled: "Без названия",
    select: "Выбор (V)",
    hand: "Рука (H)",
    sticky: "Стикер (N)",
    text: "Текст (T)",
    shape: "Фигура (S)",
    connector: "Линия со стрелкой (L)",
    pen: "Ручка (P)",
    highlighter: "Маркер",
    eraser: "Ластик (E)",
    frame: "Рамка (F)",
    shapes: { rect: "Прямоугольник", round: "Скруглённый", ellipse: "Эллипс", triangle: "Треугольник", diamond: "Ромб" },
    fill: "Заливка",
    noFill: "Без заливки",
    ink: "Цвет линии и текста",
    fontSize: "Размер текста",
    route: "Ломаная линия",
    arrow: "Стрелка на конце",
    lock: "Закрепить",
    unlock: "Открепить",
    frameTitle: "Название рамки",
    framePlaceholder: "Рамка",
    connectorLabel: "Подпись линии",
    textPlaceholder: "Текст",
    undo: "Отменить (Ctrl+Z)",
    redo: "Повторить (Ctrl+Shift+Z)",
    zoomIn: "Приблизить",
    zoomOut: "Отдалить",
    fit: "Показать всё (Shift+1)",
    colour: "Цвет стикера",
    duplicate: "Дублировать (Ctrl+D)",
    front: "На передний план",
    back2: "На задний план",
    remove: "Удалить (Delete)",
    connecting: "Подключаемся…",
    offline: "Нет связи. Изменения сохранятся, когда она вернётся.",
    readOnly: "Только просмотр",
    stickyPlaceholder: "Напишите мысль",
    emptyHint: "Нажмите N и кликните по доске, чтобы добавить стикер",
    you: "вы",
  },
} as const;
