// Every user-facing string in one place. Written fresh for Mysl; replica-brand rewrites these in the brand voice.
export const t = {
  product: "Мысль",
  login: {
    title: "Вход в Мысль",
    lead: "Доска, на которой думают вместе.",
    name: "Как вас зовут",
    email: "Электронная почта",
    submit: "Войти",
    devNote: "Тестовый вход: пароль пока не нужен.",
    errorEmail: "Проверьте адрес почты",
    linkLead: "Пришлём на почту ссылку для входа. Пароль не нужен.",
    sendLink: "Получить ссылку",
    sent: (email: string) => `Ссылка отправлена на ${email}. Откройте письмо на этом устройстве.`,
    errorSend: "Не получилось отправить письмо. Попробуйте ещё раз через минуту.",
    errorLink: "Ссылка устарела или уже использована. Запросите новую.",
    errorGoogle: "Вход через Google не удался. Попробуйте ещё раз.",
    google: "Войти через Google",
    or: "или",
    devTitle: "Тестовый вход",
  },
  dash: {
    title: "Мои доски",
    newBoard: "Новая доска",
    search: "Найти доску",
    sortOpened: "Недавно открытые",
    sortModified: "Недавно изменённые",
    sortName: "По названию",
    all: "Все",
    starred: "Избранные",
    trash: "Корзина",
    emptyTitle: "Здесь пока пусто",
    emptyBody: "Создайте первую доску: это одна кнопка.",
    emptySearch: (q: string) => `По запросу «${q}» досок нет`,
    emptyStarred: "Отметьте доску звёздочкой, и она появится здесь.",
    emptyTrash: "Корзина пуста. Удалённые доски хранятся здесь 30 дней.",
    open: "Открыть",
    rename: "Переименовать",
    star: "В избранное",
    unstar: "Убрать из избранного",
    delete: "В корзину",
    restore: "Восстановить",
    edited: "Изменена",
    signOut: "Выйти",
  },
  share: {
    open: "Поделиться",
    title: "Поделиться доской",
    close: "Закрыть",
    email: "Почта человека",
    emailPlaceholder: "name@example.com",
    role: "Доступ",
    invite: "Пригласить",
    roles: { owner: "Владелец", coowner: "Совладелец", editor: "Может редактировать", commenter: "Может комментировать", viewer: "Может смотреть" },
    added: (email: string) => `${email} теперь на доске.`,
    invited: (email: string) => `Приглашение для ${email} ждёт: доступ откроется, когда человек войдёт с этим адресом. Отправьте ему ссылку на доску.`,
    errorEmail: "Проверьте адрес почты",
    errorGeneric: "Не получилось. Попробуйте ещё раз.",
    linkTitle: "Доступ по ссылке",
    link: { private: "Только приглашённые", view: "Все со ссылкой могут смотреть", comment: "Все со ссылкой могут комментировать", edit: "Все со ссылкой могут редактировать" },
    linkNote: "По ссылке открыть доску сможет только тот, кто вошёл в Мысль.",
    copy: "Скопировать ссылку",
    copied: "Ссылка скопирована",
    people: "Кто на доске",
    you: "вы",
    pending: "ждёт входа",
    remove: "Убрать с доски",
    cancelInvite: "Отменить приглашение",
    memberRole: (name: string) => `Доступ для ${name}`,
  },
  export: {
    open: "Экспорт",
    title: "Экспорт доски",
    format: "Формат",
    png: "Картинка PNG",
    pdf: "Документ PDF",
    scope: "Что сохранить",
    board: "Всю доску",
    selection: "Выбранное",
    frames: (n: number) => `Рамки, каждую на своей странице (${n})`,
    quality: "Качество",
    q1: "Обычное",
    q2: "Высокое",
    q3: "Для печати",
    save: "Сохранить",
    saving: "Готовим файл…",
    empty: "На доске пока нечего сохранять.",
    failed: "Не получилось сохранить. Попробуйте качество пониже.",
    framesPdfOnly: "Рамки по страницам сохраняются в PDF.",
  },
  images: {
    add: "Картинка",
    uploading: "Загружаем картинку…",
    tooLarge: "Файл больше 30 МБ. Уменьшите его и попробуйте снова.",
    unsupported: "Подходят только PNG, JPEG, GIF и WebP.",
    failed: "Картинка не загрузилась. Попробуйте ещё раз.",
    untitled: "Картинка",
  },
  comments: {
    tool: "Комментарий (C)",
    pin: (author: string, text: string) => `Комментарий ${author}: ${text}`,
    resolvedPin: "решён",
    placeholder: "Напишите комментарий. @ чтобы упомянуть",
    replyPlaceholder: "Ответить. @ чтобы упомянуть",
    post: "Отправить",
    cancel: "Отмена",
    close: "Закрыть",
    resolve: "Решено",
    reopen: "Открыть снова",
    showResolved: "Показать решённые",
    hideResolved: "Скрыть решённые",
    thread: "Обсуждение",
    mentionList: "Кого упомянуть",
    error: "Не отправилось. Попробуйте ещё раз.",
    readOnly: "Комментировать могут участники с доступом к комментариям.",
    mentions: (n: number) => (n === 1 ? "1 новое упоминание" : `Новых упоминаний: ${n}`),
  },
  frames: {
    open: "Рамки",
    title: "Рамки",
    close: "Закрыть панель рамок",
    empty: "Рамок пока нет. Нажмите F, чтобы обвести выбранное рамкой или нарисовать новую.",
    untitled: "Рамка без названия",
    show: (name: string) => `Показать: ${name}`,
    rename: (name: string) => `Переименовать: ${name}`,
    nameLabel: "Название рамки",
  },
  board: {
    back: "Все доски",
    untitled: "Без названия",
    select: "Выбор (V)",
    hand: "Рука (H)",
    sticky: "Стикер (N)",
    text: "Текст (T)",
    shape: "Фигура (S)",
    connector: "Линия со стрелкой (L)",
    pen: "Ручка (P)",
    highlighter: "Маркер",
    eraser: "Ластик (E)",
    frame: "Рамка (F)",
    shapes: { rect: "Прямоугольник", round: "Скруглённый", ellipse: "Эллипс", triangle: "Треугольник", diamond: "Ромб" },
    fill: "Заливка",
    noFill: "Без заливки",
    ink: "Цвет линии и текста",
    fontSize: "Размер текста",
    routes: { label: "Вид линии", straight: "Прямая линия", elbow: "Ломаная линия", curved: "Плавная линия" },
    textStyle: "Начертание",
    bold: "Жирный (Ctrl+B)",
    italic: "Курсив (Ctrl+I)",
    underline: "Подчёркнутый (Ctrl+U)",
    lasso: "Лассо (O)",
    group: "Сгруппировать (Ctrl+G)",
    ungroup: "Разгруппировать (Ctrl+Shift+G)",
    inGroup: "в группе",
    copy: "Копировать (Ctrl+C)",
    pasted: (n: number) => (n === 1 ? "Вставлен 1 объект" : `Вставлено объектов: ${n}`),
    arrow: "Стрелка на конце",
    lock: "Закрепить",
    unlock: "Открепить",
    frameTitle: "Название рамки",
    framePlaceholder: "Рамка",
    connectorLabel: "Подпись линии",
    textPlaceholder: "Текст",
    undo: "Отменить (Ctrl+Z)",
    redo: "Повторить (Ctrl+Shift+Z)",
    zoomIn: "Приблизить",
    zoomOut: "Отдалить",
    fit: "Показать всё (Shift+1)",
    colour: "Цвет стикера",
    duplicate: "Дублировать (Ctrl+D)",
    front: "На передний план",
    back2: "На задний план",
    remove: "Удалить (Delete)",
    connecting: "Подключаемся…",
    offline: "Нет связи. Изменения сохранятся, когда она вернётся.",
    readOnly: "Только просмотр",
    stickyPlaceholder: "Напишите мысль",
    emptyHint: "Нажмите N и кликните по доске, чтобы добавить стикер",
    you: "вы",
  },
} as const;
