-- All migrations in one file, for pasting into the Supabase SQL Editor when `npm run db:migrate` cannot reach the database.
-- Generated by scripts/bundle-migrations.ts; do not edit by hand. It records each migration, so a later `npm run db:migrate` skips them.
-- Do not run it twice: the second run stops at the first table that already exists and changes nothing.
begin;
create table if not exists schema_migrations (name text primary key, applied_at timestamptz not null default now());

-- ===== 0001_init.sql =====
-- Mysl: first migration. Postgres 15+ on Supabase.
-- Board content (items) lives in a Yjs CRDT document per board, stored in board_docs.
-- Relational tables hold everything that needs auth, querying or billing.
-- Access rule: row level security on every table; the realtime server uses the service role
-- and checks membership through can_access_board() before accepting a connection.

create extension if not exists pgcrypto;
create extension if not exists pg_trgm;

-- profiles mirror auth.users (Supabase Auth owns credentials)
create table profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null default '',
  email text not null,
  avatar_url text,
  input_mode text not null default 'auto' check (input_mode in ('auto','mouse','trackpad')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index on profiles (lower(email));

create table teams (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 1 and 80),
  plan text not null default 'free' check (plan in ('free','starter','business')),
  stripe_customer_id text unique,
  created_by uuid not null references profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table team_members (
  team_id uuid not null references teams(id) on delete cascade,
  user_id uuid not null references profiles(id) on delete cascade,
  role text not null default 'member' check (role in ('owner','admin','member')),
  created_at timestamptz not null default now(),
  primary key (team_id, user_id)
);
create index on team_members (user_id);

create table boards (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references teams(id) on delete cascade,
  owner_id uuid not null references profiles(id) on delete restrict,
  name text not null default 'Untitled' check (char_length(name) between 1 and 60),
  description text not null default '' check (char_length(description) <= 300),
  link_access text not null default 'private' check (link_access in ('private','view','comment','edit')),
  team_access text not null default 'edit' check (team_access in ('private','view','comment','edit')),
  link_token text not null unique default encode(gen_random_bytes(16), 'hex'),
  thumbnail_path text,
  deleted_at timestamptz,                 -- trash; purged after 30 days by a job
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index on boards (team_id, updated_at desc) where deleted_at is null;
create index on boards (owner_id);
create index boards_name_trgm on boards using gin (name gin_trgm_ops);

create table board_members (
  board_id uuid not null references boards(id) on delete cascade,
  user_id uuid not null references profiles(id) on delete cascade,
  role text not null check (role in ('owner','coowner','editor','commenter','viewer')),
  starred boolean not null default false,
  last_opened_at timestamptz,
  created_at timestamptz not null default now(),
  primary key (board_id, user_id)
);
create index on board_members (user_id, last_opened_at desc);

create table board_invites (
  id uuid primary key default gen_random_uuid(),
  board_id uuid not null references boards(id) on delete cascade,
  email text not null,
  role text not null check (role in ('editor','commenter','viewer')),
  invited_by uuid not null references profiles(id) on delete cascade,
  accepted_at timestamptz,
  created_at timestamptz not null default now(),
  unique (board_id, email)
);

-- Current CRDT state, written by the realtime server (debounced) and on last disconnect
create table board_docs (
  board_id uuid primary key references boards(id) on delete cascade,
  state bytea not null,                   -- Y.encodeStateAsUpdate
  item_count int not null default 0,
  updated_at timestamptz not null default now()
);

-- Version history: hourly snapshot while a board is being edited
create table board_versions (
  id uuid primary key default gen_random_uuid(),
  board_id uuid not null references boards(id) on delete cascade,
  state bytea not null,
  created_at timestamptz not null default now()
);
create index on board_versions (board_id, created_at desc);

-- Plain-text mirror of item content for search on board and across boards
create table item_search (
  board_id uuid not null references boards(id) on delete cascade,
  item_id text not null,                  -- Yjs item id (nanoid)
  item_type text not null,
  body text not null,
  primary key (board_id, item_id)
);
create index item_search_trgm on item_search using gin (body gin_trgm_ops);

create table assets (
  id uuid primary key default gen_random_uuid(),
  board_id uuid not null references boards(id) on delete cascade,
  uploaded_by uuid references profiles(id) on delete set null,
  storage_path text not null unique,
  mime text not null check (mime in ('image/png','image/jpeg','image/gif','image/webp','image/svg+xml','application/pdf')),
  bytes int not null check (bytes between 1 and 31457280),   -- 30 MB
  width int, height int,
  created_at timestamptz not null default now()
);
create index on assets (board_id);

create table comment_threads (
  id uuid primary key default gen_random_uuid(),
  board_id uuid not null references boards(id) on delete cascade,
  item_id text,                           -- null = pinned to a canvas point
  x double precision not null,
  y double precision not null,
  resolved_at timestamptz,
  resolved_by uuid references profiles(id) on delete set null,
  created_by uuid not null references profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);
create index on comment_threads (board_id, created_at);

create table comments (
  id uuid primary key default gen_random_uuid(),
  thread_id uuid not null references comment_threads(id) on delete cascade,
  author_id uuid not null references profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 5000),
  edited_at timestamptz,
  created_at timestamptz not null default now()
);
create index on comments (thread_id, created_at);
create index on comments (author_id);

create table notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references profiles(id) on delete cascade,
  kind text not null check (kind in ('mention','invite','comment_reply','thread_resolved')),
  board_id uuid references boards(id) on delete cascade,
  comment_id uuid references comments(id) on delete cascade,
  actor_id uuid references profiles(id) on delete set null,
  read_at timestamptz,
  emailed_at timestamptz,
  created_at timestamptz not null default now()
);
create index on notifications (user_id, created_at desc) where read_at is null;

create table templates (
  id uuid primary key default gen_random_uuid(),
  team_id uuid references teams(id) on delete cascade,   -- null = built-in, written by us
  name text not null,
  category text not null,
  state bytea not null,
  preview_path text,
  created_by uuid references profiles(id) on delete set null,
  created_at timestamptz not null default now()
);
create index on templates (team_id, category);

create table subscriptions (
  team_id uuid primary key references teams(id) on delete cascade,
  stripe_subscription_id text not null unique,
  status text not null check (status in ('trialing','active','past_due','canceled','incomplete','unpaid')),
  plan text not null check (plan in ('starter','business')),
  seats int not null check (seats > 0),
  current_period_end timestamptz not null,
  cancel_at_period_end boolean not null default false,
  updated_at timestamptz not null default now()
);

create table stripe_events (
  id text primary key,                    -- Stripe event id, makes webhooks idempotent
  type text not null,
  received_at timestamptz not null default now()
);

-- Authorisation in one place (security definer so policies do not recurse into team_members)
create or replace function is_team_member(t uuid, u uuid, roles text[] default array['owner','admin','member']) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from team_members where team_id = t and user_id = u and role = any(roles));
$$;

create or replace function board_role(b uuid, u uuid) returns text
language sql stable security definer set search_path = public as $$
  select coalesce(
    (select role from board_members where board_id = b and user_id = u),
    (select case when bo.team_access <> 'private' and exists
              (select 1 from team_members tm where tm.team_id = bo.team_id and tm.user_id = u)
            then case bo.team_access when 'edit' then 'editor' when 'comment' then 'commenter' else 'viewer' end end
       from boards bo where bo.id = b and bo.deleted_at is null)
  );
$$;

create or replace function can_access_board(b uuid, u uuid, need text) returns boolean
language sql stable as $$
  select case need
    when 'view'    then board_role(b,u) is not null
    when 'comment' then board_role(b,u) in ('owner','coowner','editor','commenter')
    when 'edit'    then board_role(b,u) in ('owner','coowner','editor')
    when 'manage'  then board_role(b,u) in ('owner','coowner')
  end;
$$;

alter table profiles enable row level security;
alter table teams enable row level security;
alter table team_members enable row level security;
alter table boards enable row level security;
alter table board_members enable row level security;
alter table board_invites enable row level security;
alter table board_docs enable row level security;
alter table board_versions enable row level security;
alter table item_search enable row level security;
alter table assets enable row level security;
alter table comment_threads enable row level security;
alter table comments enable row level security;
alter table notifications enable row level security;
alter table templates enable row level security;
alter table subscriptions enable row level security;
alter table stripe_events enable row level security;   -- no policies: service role only

create policy own_profile on profiles for all using (id = auth.uid());
create policy team_read on teams for select using (is_team_member(id, auth.uid()));
create policy team_members_read on team_members for select using (is_team_member(team_id, auth.uid()));
create policy boards_read on boards for select using (can_access_board(id, auth.uid(), 'view'));
create policy boards_update on boards for update using (can_access_board(id, auth.uid(), 'manage'));
create policy boards_insert on boards for insert with check (owner_id = auth.uid() and is_team_member(team_id, auth.uid()));
create policy members_read on board_members for select using (can_access_board(board_id, auth.uid(), 'view'));
create policy members_manage on board_members for all using (can_access_board(board_id, auth.uid(), 'manage'));
create policy members_star_self on board_members for update using (user_id = auth.uid());
create policy invites_manage on board_invites for all using (can_access_board(board_id, auth.uid(), 'manage'));
create policy versions_read on board_versions for select using (can_access_board(board_id, auth.uid(), 'view'));
create policy search_read on item_search for select using (can_access_board(board_id, auth.uid(), 'view'));
create policy assets_read on assets for select using (can_access_board(board_id, auth.uid(), 'view'));
create policy assets_insert on assets for insert with check (can_access_board(board_id, auth.uid(), 'edit'));
create policy threads_read on comment_threads for select using (can_access_board(board_id, auth.uid(), 'view'));
create policy threads_write on comment_threads for insert with check (can_access_board(board_id, auth.uid(), 'comment') and created_by = auth.uid());
create policy threads_resolve on comment_threads for update using (can_access_board(board_id, auth.uid(), 'comment'));
create policy comments_read on comments for select using (exists (select 1 from comment_threads t where t.id = thread_id and can_access_board(t.board_id, auth.uid(), 'view')));
create policy comments_write on comments for insert with check (author_id = auth.uid() and exists (select 1 from comment_threads t where t.id = thread_id and can_access_board(t.board_id, auth.uid(), 'comment')));
create policy comments_edit_own on comments for update using (author_id = auth.uid());
create policy notifications_own on notifications for all using (user_id = auth.uid());
create policy templates_read on templates for select using (team_id is null or is_team_member(team_id, auth.uid()));
create policy subs_read on subscriptions for select using (is_team_member(team_id, auth.uid(), array['owner','admin']));
-- board_docs: no client policies; only the realtime server (service role) reads and writes.

-- ---------- triggers ----------

-- A new account gets a profile and a personal team.
create or replace function handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
declare
  team uuid;
  display text := coalesce(nullif(new.raw_user_meta_data->>'name', ''), split_part(new.email, '@', 1));
begin
  insert into profiles (id, name, email) values (new.id, display, lower(new.email));
  insert into teams (name, created_by) values (display, new.id) returning id into team;
  insert into team_members (team_id, user_id, role) values (team, new.id, 'owner');
  return new;
end;
$$;
create trigger on_auth_user_created after insert on auth.users for each row execute function handle_new_user();

-- Whoever creates a board owns it.
create or replace function handle_new_board() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into board_members (board_id, user_id, role, last_opened_at) values (new.id, new.owner_id, 'owner', now());
  return new;
end;
$$;
create trigger on_board_created after insert on boards for each row execute function handle_new_board();

create or replace function touch_updated_at() returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end;
$$;
create trigger boards_touch before update on boards for each row execute function touch_updated_at();

-- ---------- grants ----------
grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant execute on all functions in schema public to authenticated;
insert into schema_migrations (name) values ('0001_init.sql');

-- ===== 0002_content_time.sql =====
-- When the board's content (not its name) last changed; written by the realtime server on save.
alter table boards add column content_updated_at timestamptz;

-- Saving content is not a rename: do not bump updated_at for it.
create or replace function touch_updated_at() returns trigger language plpgsql as $$
begin
  if (new.name, new.description, new.link_access, new.team_access, new.deleted_at) is distinct from
     (old.name, old.description, old.link_access, old.team_access, old.deleted_at) then
    new.updated_at := now();
  end if;
  return new;
end;
$$;
insert into schema_migrations (name) values ('0002_content_time.sql');

-- ===== 0003_sharing.sql =====
-- Sharing: invites by email, link access, and the people list.
-- Profiles are private to their owner, so everything that crosses users goes through these
-- security definer functions, each of which checks the caller's own role first.

create or replace function link_role(access text) returns text language sql immutable as $$
  select case access when 'edit' then 'editor' when 'comment' then 'commenter' when 'view' then 'viewer' end;
$$;

-- Everyone on the board plus pending invites, for anyone who can see the board.
create or replace function board_people(b uuid)
returns table (user_id uuid, name text, email text, role text, pending boolean)
language plpgsql stable security definer set search_path = public as $$
begin
  if board_role(b, auth.uid()) is null then raise exception 'no access' using errcode = '42501'; end if;
  return query
    select x.uid, x.nm, x.em, x.rl, x.pend from (
      select p.id as uid, p.name as nm, p.email as em, m.role as rl, false as pend
        from board_members m join profiles p on p.id = m.user_id
       where m.board_id = b
      union all
      select null::uuid, ''::text, i.email, i.role, true
        from board_invites i
       where i.board_id = b and i.accepted_at is null
    ) x
    order by x.pend, array_position(array['owner','coowner','editor','commenter','viewer'], x.rl), x.nm, x.em;
end;
$$;

-- Owner or co-owner adds someone by email. An existing account joins at once; anyone else gets
-- a pending invite that turns into membership when they sign up with that address.
create or replace function share_board(b uuid, invitee text, new_role text) returns text
language plpgsql security definer set search_path = public as $$
declare
  key text := lower(trim(invitee));
  uid uuid;
begin
  if coalesce(board_role(b, auth.uid()), '') not in ('owner', 'coowner') then raise exception 'no access' using errcode = '42501'; end if;
  if new_role not in ('editor', 'commenter', 'viewer') then raise exception 'bad role' using errcode = '22023'; end if;
  select id into uid from profiles where email = key;
  if uid is not null then
    insert into board_members (board_id, user_id, role) values (b, uid, new_role)
      on conflict (board_id, user_id) do update set role = excluded.role
      where board_members.role not in ('owner', 'coowner');
    return 'added';
  end if;
  insert into board_invites (board_id, email, role, invited_by) values (b, key, new_role, auth.uid())
    on conflict (board_id, email) do update set role = excluded.role, accepted_at = null;
  return 'invited';
end;
$$;

-- Change a member's role, or remove them with new_role = null. The owner cannot be changed.
create or replace function set_member_role(b uuid, member uuid, new_role text) returns void
language plpgsql security definer set search_path = public as $$
begin
  if coalesce(board_role(b, auth.uid()), '') not in ('owner', 'coowner') then raise exception 'no access' using errcode = '42501'; end if;
  if new_role is not null and new_role not in ('editor', 'commenter', 'viewer') then raise exception 'bad role' using errcode = '22023'; end if;
  if (select role from board_members where board_id = b and user_id = member) = 'owner' then
    raise exception 'owner cannot be changed' using errcode = '42501';
  end if;
  if new_role is null then
    delete from board_members where board_id = b and user_id = member;
  else
    update board_members set role = new_role where board_id = b and user_id = member;
  end if;
end;
$$;

create or replace function cancel_invite(b uuid, invitee text) returns void
language plpgsql security definer set search_path = public as $$
begin
  if coalesce(board_role(b, auth.uid()), '') not in ('owner', 'coowner') then raise exception 'no access' using errcode = '42501'; end if;
  delete from board_invites where board_id = b and email = lower(trim(invitee)) and accepted_at is null;
end;
$$;

-- Someone signed in opens a board shared by link: they become a member with the link's role,
-- so the board shows up in their list. Returns their role, or null when the link is off.
create or replace function join_board_via_link(b uuid) returns text
language plpgsql security definer set search_path = public as $$
declare
  current text := board_role(b, auth.uid());
  via text;
begin
  if auth.uid() is null then return null; end if;
  if current is not null then return current; end if;
  select link_role(link_access) into via from boards where id = b and deleted_at is null;
  if via is null then return null; end if;
  insert into board_members (board_id, user_id, role) values (b, auth.uid(), via) on conflict do nothing;
  return via;
end;
$$;

-- New accounts pick up the invites waiting for their address.
create or replace function handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
declare
  team uuid;
  display text := coalesce(nullif(new.raw_user_meta_data->>'name', ''), nullif(new.raw_user_meta_data->>'full_name', ''), split_part(new.email, '@', 1));
begin
  insert into profiles (id, name, email) values (new.id, display, lower(new.email));
  insert into teams (name, created_by) values (display, new.id) returning id into team;
  insert into team_members (team_id, user_id, role) values (team, new.id, 'owner');
  insert into board_members (board_id, user_id, role)
    select board_id, new.id, role from board_invites where email = lower(new.email) and accepted_at is null
    on conflict do nothing;
  update board_invites set accepted_at = now() where email = lower(new.email) and accepted_at is null;
  return new;
end;
$$;

revoke execute on function board_people(uuid), share_board(uuid, text, text), set_member_role(uuid, uuid, text),
  cancel_invite(uuid, text), join_board_via_link(uuid) from public, anon;

grant execute on function board_people(uuid), share_board(uuid, text, text), set_member_role(uuid, uuid, text),
  cancel_invite(uuid, text), join_board_via_link(uuid), link_role(text) to authenticated;
insert into schema_migrations (name) values ('0003_sharing.sql');

-- ===== 0004_comments.sql =====
-- Comments: reading needs author names across users, and mentions notify other people,
-- so both go through security definer functions that check the caller's access first.

create or replace function board_comments(b uuid)
returns table (thread_id uuid, item_id text, x double precision, y double precision, resolved boolean, thread_created_by uuid,
               thread_created_at timestamptz, comment_id uuid, author_id uuid, author_name text, body text, created_at timestamptz)
language plpgsql stable security definer set search_path = public as $$
begin
  if board_role(b, auth.uid()) is null then raise exception 'no access' using errcode = '42501'; end if;
  return query
    select t.id, t.item_id, t.x, t.y, t.resolved_at is not null, t.created_by, t.created_at,
           c.id, c.author_id, coalesce(p.name, ''), c.body, c.created_at
      from comment_threads t
      join comments c on c.thread_id = t.id
      left join profiles p on p.id = c.author_id
     where t.board_id = b
     order by t.created_at, c.created_at;
end;
$$;

-- The author of a comment notifies the people they mentioned; only people on the board are notified.
create or replace function notify_mentions(comment uuid, mentioned uuid[]) returns int
language plpgsql security definer set search_path = public as $$
declare
  b uuid;
  n int;
begin
  select t.board_id into b from comments c join comment_threads t on t.id = c.thread_id
   where c.id = comment and c.author_id = auth.uid();
  if b is null then raise exception 'no access' using errcode = '42501'; end if;
  insert into notifications (user_id, kind, board_id, comment_id, actor_id)
    select distinct u, 'mention', b, comment, auth.uid()
      from unnest(mentioned) as u
     where u <> auth.uid() and board_role(b, u) is not null;
  get diagnostics n = row_count;
  return n;
end;
$$;

revoke execute on function board_comments(uuid), notify_mentions(uuid, uuid[]) from public, anon;
grant execute on function board_comments(uuid), notify_mentions(uuid, uuid[]) to authenticated;
insert into schema_migrations (name) values ('0004_comments.sql');

-- ===== 0005_assets_bucket.sql =====
-- Images live in a private Supabase Storage bucket that only the server reads, with the service key.
-- On plain Postgres (local development) there is no storage schema and this does nothing.
do $$
begin
  if exists (select 1 from information_schema.schemata where schema_name = 'storage') then
    insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
    values ('assets', 'assets', false, 31457280, array['image/png', 'image/jpeg', 'image/gif', 'image/webp'])
    on conflict (id) do nothing;
  end if;
end;
$$;
insert into schema_migrations (name) values ('0005_assets_bucket.sql');

-- ===== 0006_notifications.sql =====
-- Notifications panel, invite notifications, board duplicate and trash purge.
-- The notifications table itself comes from 0001 (row level security on, policy notifications_own:
-- a person reads and changes only rows with their own user_id). Anything that crosses users goes
-- through the security definer functions below, each of which checks the caller first.

-- An index for the panel, which lists read and unread rows together.
create index if not exists notifications_user_created on notifications (user_id, created_at desc);

-- The panel: the caller's own notifications on boards they can still open, with the board name,
-- who did it and the comment text. Profiles and comments are private, hence security definer.
create or replace function my_notifications(lim int default 50)
returns table (id uuid, kind text, board_id uuid, board_name text, actor_name text, excerpt text, read boolean, created_at timestamptz)
language sql stable security definer set search_path = public as $$
  select n.id, n.kind, n.board_id, b.name, coalesce(p.name, ''), coalesce(c.body, ''), n.read_at is not null, n.created_at
    from notifications n
    join boards b on b.id = n.board_id and b.deleted_at is null
    left join profiles p on p.id = n.actor_id
    left join comments c on c.id = n.comment_id
   where n.user_id = auth.uid()
     and n.kind in ('mention', 'invite')
     and board_role(n.board_id, auth.uid()) is not null
   order by n.created_at desc
   limit least(greatest(coalesce(lim, 50), 1), 200);
$$;

-- Sharing with someone who already has an account adds them at once and tells them so.
create or replace function share_board(b uuid, invitee text, new_role text) returns text
language plpgsql security definer set search_path = public as $$
declare
  key text := lower(trim(invitee));
  uid uuid;
  existed boolean;
begin
  if coalesce(board_role(b, auth.uid()), '') not in ('owner', 'coowner') then raise exception 'no access' using errcode = '42501'; end if;
  if new_role not in ('editor', 'commenter', 'viewer') then raise exception 'bad role' using errcode = '22023'; end if;
  select id into uid from profiles where email = key;
  if uid is not null then
    existed := exists (select 1 from board_members where board_id = b and user_id = uid);
    insert into board_members (board_id, user_id, role) values (b, uid, new_role)
      on conflict (board_id, user_id) do update set role = excluded.role
      where board_members.role not in ('owner', 'coowner');
    if not existed and uid <> auth.uid() then
      insert into notifications (user_id, kind, board_id, actor_id) values (uid, 'invite', b, auth.uid());
    end if;
    return 'added';
  end if;
  insert into board_invites (board_id, email, role, invited_by) values (b, key, new_role, auth.uid())
    on conflict (board_id, email) do update set role = excluded.role, accepted_at = null;
  return 'invited';
end;
$$;

-- New accounts pick up the invites waiting for their address, and see who invited them.
create or replace function handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
declare
  team uuid;
  display text := coalesce(nullif(new.raw_user_meta_data->>'name', ''), nullif(new.raw_user_meta_data->>'full_name', ''), split_part(new.email, '@', 1));
begin
  insert into profiles (id, name, email) values (new.id, display, lower(new.email));
  insert into teams (name, created_by) values (display, new.id) returning id into team;
  insert into team_members (team_id, user_id, role) values (team, new.id, 'owner');
  insert into board_members (board_id, user_id, role)
    select board_id, new.id, role from board_invites where email = lower(new.email) and accepted_at is null
    on conflict do nothing;
  insert into notifications (user_id, kind, board_id, actor_id)
    select new.id, 'invite', board_id, invited_by from board_invites where email = lower(new.email) and accepted_at is null;
  update board_invites set accepted_at = now() where email = lower(new.email) and accepted_at is null;
  return new;
end;
$$;

-- Duplicate: the copy's images get their own asset rows over the same stored files, so a file
-- can now belong to several rows. The trash purge deletes a file only when no row uses it.
alter table assets drop constraint if exists assets_storage_path_key;
create index if not exists assets_storage_path on assets (storage_path);

-- Board content is written only by the realtime server (no client policies on board_docs).
-- Duplicating reads the source content as someone who may edit it...
create or replace function board_doc_state(b uuid) returns bytea
language plpgsql stable security definer set search_path = public as $$
begin
  if coalesce(board_role(b, auth.uid()), '') not in ('owner', 'coowner', 'editor') then raise exception 'no access' using errcode = '42501'; end if;
  return (select state from board_docs where board_id = b);
end;
$$;

-- ...and writes the first content of the copy, which only its owner may do, and only once.
create or replace function seed_board_doc(b uuid, s bytea) returns void
language plpgsql security definer set search_path = public as $$
begin
  if coalesce(board_role(b, auth.uid()), '') <> 'owner' then raise exception 'no access' using errcode = '42501'; end if;
  insert into board_docs (board_id, state, updated_at) values (b, s, now());
end;
$$;

revoke execute on function my_notifications(int), board_doc_state(uuid), seed_board_doc(uuid, bytea) from public, anon;
grant execute on function my_notifications(int), board_doc_state(uuid), seed_board_doc(uuid, bytea), share_board(uuid, text, text) to authenticated;
insert into schema_migrations (name) values ('0006_notifications.sql');

-- ===== 0007_billing.sql =====
-- Billing: Free and Pro per person, paid through Stripe (test mode until launch).
-- The plan belongs to a board's owner: their plan sets the editor limit on their boards and
-- the storage for everything uploaded to them.
--
-- Who writes what:
--   * subscriptions rows are written only by the server's service connection, from verified
--     Stripe webhooks (app/api/stripe/webhook) and when a checkout customer is created.
--     There are no insert/update/delete policies, so the authenticated role cannot change them.
--   * a person reads only their own row.
--   * stripe_events (from 0001) records processed event ids so a repeated delivery changes nothing.

-- The team-based draft table from 0001 was never written by any code; billing is per person.
drop table if exists subscriptions;

create table subscriptions (
  user_id uuid primary key references profiles(id) on delete cascade,
  stripe_customer_id text unique,
  stripe_subscription_id text unique,
  plan text not null default 'free' check (plan in ('free', 'pro')),
  status text not null default 'none'
    check (status in ('none', 'trialing', 'active', 'past_due', 'canceled', 'incomplete', 'incomplete_expired', 'unpaid', 'paused')),
  current_period_end timestamptz,
  cancel_at_period_end boolean not null default false,
  last_event_at timestamptz,               -- Stripe event time of the last change; older events are ignored
  updated_at timestamptz not null default now()
);

alter table subscriptions enable row level security;
create policy subscriptions_read_own on subscriptions for select using (user_id = auth.uid());
revoke all on subscriptions from anon, authenticated;
grant select on subscriptions to authenticated;

revoke all on stripe_events from anon, authenticated;

-- Opening a board by an edit link when the owner's plan has no editor seats left: the person
-- joins with a lower role instead. The app decides the cap; the old one-argument form stays.
create or replace function join_board_via_link(b uuid, cap text) returns text
language plpgsql security definer set search_path = public as $$
declare
  current text := board_role(b, auth.uid());
  via text;
begin
  if auth.uid() is null then return null; end if;
  if current is not null then return current; end if;
  if cap is not null and cap not in ('commenter', 'viewer') then raise exception 'bad role' using errcode = '22023'; end if;
  select link_role(link_access) into via from boards where id = b and deleted_at is null;
  if via is null then return null; end if;
  if via = 'editor' and cap is not null then via := cap; end if;
  insert into board_members (board_id, user_id, role) values (b, auth.uid(), via) on conflict do nothing;
  return via;
end;
$$;

revoke execute on function join_board_via_link(uuid, text) from public, anon;
grant execute on function join_board_via_link(uuid, text) to authenticated;
insert into schema_migrations (name) values ('0007_billing.sql');

-- ===== 0008_guest_links.sql =====
-- Guest links: people who are not signed in may view a board through its link, read-only.
--
-- A link is the board id plus the board's secret (boards.link_token, 128 random bits from 0001).
-- A board id alone is never enough: joining by link and viewing as a guest both check the secret.
-- Owners and co-owners can make a new secret (an ordinary update through boards_update), which
-- stops every link given out before.
--
-- Guests use Supabase's anon role. They reach nothing through tables (row level security needs
-- auth.uid()), only through the two guest_* functions below, which return the board's id and name
-- and the images on that one board. Board content comes from the realtime server, which checks the
-- secret through the web app before it hands out a read-only token.

alter table boards add column if not exists guest_view boolean not null default false;

-- Opening by link needs the secret. The old forms took the board id alone: drop them, so nobody can
-- call them through the API either.
drop function if exists join_board_via_link(uuid);
drop function if exists join_board_via_link(uuid, text);

create or replace function join_board_via_link(b uuid, secret text, cap text) returns text
language plpgsql security definer set search_path = public as $$
declare
  current text := board_role(b, auth.uid());
  via text;
begin
  if auth.uid() is null then return null; end if;
  if current is not null then return current; end if;
  if cap is not null and cap not in ('commenter', 'viewer') then raise exception 'bad role' using errcode = '22023'; end if;
  if secret is null or length(secret) < 32 then return null; end if;
  select link_role(link_access) into via from boards where id = b and deleted_at is null and link_token = secret;
  if via is null then return null; end if;
  if via = 'editor' and cap is not null then via := cap; end if;
  insert into board_members (board_id, user_id, role) values (b, auth.uid(), via) on conflict do nothing;
  return via;
end;
$$;

-- A guest holding the link: the board's id and name, when the link is on, guest viewing is on and
-- the secret matches. Nothing else about the board (no owner, no people, no emails).
create or replace function guest_board(b uuid, secret text)
returns table (id uuid, name text)
language sql stable security definer set search_path = public as $$
  select bo.id, bo.name from boards bo
   where bo.id = b and bo.deleted_at is null and bo.guest_view and bo.link_access <> 'private'
     and secret is not null and length(secret) >= 32 and bo.link_token = secret;
$$;

-- An image for a guest: only one on the board whose secret they hold.
create or replace function guest_asset(a uuid, secret text)
returns table (id uuid, board_id uuid, storage_path text, mime text, bytes int, width int, height int)
language sql stable security definer set search_path = public as $$
  select x.id, x.board_id, x.storage_path, x.mime, x.bytes, x.width, x.height
    from assets x join boards bo on bo.id = x.board_id
   where x.id = a and bo.deleted_at is null and bo.guest_view and bo.link_access <> 'private'
     and secret is not null and length(secret) >= 32 and bo.link_token = secret;
$$;

revoke execute on function join_board_via_link(uuid, text, text), guest_board(uuid, text), guest_asset(uuid, text) from public;
grant execute on function join_board_via_link(uuid, text, text) to authenticated;
grant execute on function guest_board(uuid, text), guest_asset(uuid, text) to anon, authenticated;
insert into schema_migrations (name) values ('0008_guest_links.sql');
commit;
