-- Migrations 0006_notifications.sql to 0007_billing.sql in one file, for a Supabase database that already has the earlier ones.
-- Generated by scripts/bundle-migrations.ts; do not edit by hand. It records each migration, so a later `npm run db:migrate` skips them.
-- Do not run it twice: the second run stops at the first table that already exists and changes nothing.
begin;
create table if not exists schema_migrations (name text primary key, applied_at timestamptz not null default now());

-- ===== 0006_notifications.sql =====
-- Notifications panel, invite notifications, board duplicate and trash purge.
-- The notifications table itself comes from 0001 (row level security on, policy notifications_own:
-- a person reads and changes only rows with their own user_id). Anything that crosses users goes
-- through the security definer functions below, each of which checks the caller first.

-- An index for the panel, which lists read and unread rows together.
create index if not exists notifications_user_created on notifications (user_id, created_at desc);

-- The panel: the caller's own notifications on boards they can still open, with the board name,
-- who did it and the comment text. Profiles and comments are private, hence security definer.
create or replace function my_notifications(lim int default 50)
returns table (id uuid, kind text, board_id uuid, board_name text, actor_name text, excerpt text, read boolean, created_at timestamptz)
language sql stable security definer set search_path = public as $$
  select n.id, n.kind, n.board_id, b.name, coalesce(p.name, ''), coalesce(c.body, ''), n.read_at is not null, n.created_at
    from notifications n
    join boards b on b.id = n.board_id and b.deleted_at is null
    left join profiles p on p.id = n.actor_id
    left join comments c on c.id = n.comment_id
   where n.user_id = auth.uid()
     and n.kind in ('mention', 'invite')
     and board_role(n.board_id, auth.uid()) is not null
   order by n.created_at desc
   limit least(greatest(coalesce(lim, 50), 1), 200);
$$;

-- Sharing with someone who already has an account adds them at once and tells them so.
create or replace function share_board(b uuid, invitee text, new_role text) returns text
language plpgsql security definer set search_path = public as $$
declare
  key text := lower(trim(invitee));
  uid uuid;
  existed boolean;
begin
  if coalesce(board_role(b, auth.uid()), '') not in ('owner', 'coowner') then raise exception 'no access' using errcode = '42501'; end if;
  if new_role not in ('editor', 'commenter', 'viewer') then raise exception 'bad role' using errcode = '22023'; end if;
  select id into uid from profiles where email = key;
  if uid is not null then
    existed := exists (select 1 from board_members where board_id = b and user_id = uid);
    insert into board_members (board_id, user_id, role) values (b, uid, new_role)
      on conflict (board_id, user_id) do update set role = excluded.role
      where board_members.role not in ('owner', 'coowner');
    if not existed and uid <> auth.uid() then
      insert into notifications (user_id, kind, board_id, actor_id) values (uid, 'invite', b, auth.uid());
    end if;
    return 'added';
  end if;
  insert into board_invites (board_id, email, role, invited_by) values (b, key, new_role, auth.uid())
    on conflict (board_id, email) do update set role = excluded.role, accepted_at = null;
  return 'invited';
end;
$$;

-- New accounts pick up the invites waiting for their address, and see who invited them.
create or replace function handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
declare
  team uuid;
  display text := coalesce(nullif(new.raw_user_meta_data->>'name', ''), nullif(new.raw_user_meta_data->>'full_name', ''), split_part(new.email, '@', 1));
begin
  insert into profiles (id, name, email) values (new.id, display, lower(new.email));
  insert into teams (name, created_by) values (display, new.id) returning id into team;
  insert into team_members (team_id, user_id, role) values (team, new.id, 'owner');
  insert into board_members (board_id, user_id, role)
    select board_id, new.id, role from board_invites where email = lower(new.email) and accepted_at is null
    on conflict do nothing;
  insert into notifications (user_id, kind, board_id, actor_id)
    select new.id, 'invite', board_id, invited_by from board_invites where email = lower(new.email) and accepted_at is null;
  update board_invites set accepted_at = now() where email = lower(new.email) and accepted_at is null;
  return new;
end;
$$;

-- Duplicate: the copy's images get their own asset rows over the same stored files, so a file
-- can now belong to several rows. The trash purge deletes a file only when no row uses it.
alter table assets drop constraint if exists assets_storage_path_key;
create index if not exists assets_storage_path on assets (storage_path);

-- Board content is written only by the realtime server (no client policies on board_docs).
-- Duplicating reads the source content as someone who may edit it...
create or replace function board_doc_state(b uuid) returns bytea
language plpgsql stable security definer set search_path = public as $$
begin
  if coalesce(board_role(b, auth.uid()), '') not in ('owner', 'coowner', 'editor') then raise exception 'no access' using errcode = '42501'; end if;
  return (select state from board_docs where board_id = b);
end;
$$;

-- ...and writes the first content of the copy, which only its owner may do, and only once.
create or replace function seed_board_doc(b uuid, s bytea) returns void
language plpgsql security definer set search_path = public as $$
begin
  if coalesce(board_role(b, auth.uid()), '') <> 'owner' then raise exception 'no access' using errcode = '42501'; end if;
  insert into board_docs (board_id, state, updated_at) values (b, s, now());
end;
$$;

revoke execute on function my_notifications(int), board_doc_state(uuid), seed_board_doc(uuid, bytea) from public, anon;
grant execute on function my_notifications(int), board_doc_state(uuid), seed_board_doc(uuid, bytea), share_board(uuid, text, text) to authenticated;
insert into schema_migrations (name) values ('0006_notifications.sql');

-- ===== 0007_billing.sql =====
-- Billing: Free and Pro per person, paid through Stripe (test mode until launch).
-- The plan belongs to a board's owner: their plan sets the editor limit on their boards and
-- the storage for everything uploaded to them.
--
-- Who writes what:
--   * subscriptions rows are written only by the server's service connection, from verified
--     Stripe webhooks (app/api/stripe/webhook) and when a checkout customer is created.
--     There are no insert/update/delete policies, so the authenticated role cannot change them.
--   * a person reads only their own row.
--   * stripe_events (from 0001) records processed event ids so a repeated delivery changes nothing.

-- The team-based draft table from 0001 was never written by any code; billing is per person.
drop table if exists subscriptions;

create table subscriptions (
  user_id uuid primary key references profiles(id) on delete cascade,
  stripe_customer_id text unique,
  stripe_subscription_id text unique,
  plan text not null default 'free' check (plan in ('free', 'pro')),
  status text not null default 'none'
    check (status in ('none', 'trialing', 'active', 'past_due', 'canceled', 'incomplete', 'incomplete_expired', 'unpaid', 'paused')),
  current_period_end timestamptz,
  cancel_at_period_end boolean not null default false,
  last_event_at timestamptz,               -- Stripe event time of the last change; older events are ignored
  updated_at timestamptz not null default now()
);

alter table subscriptions enable row level security;
create policy subscriptions_read_own on subscriptions for select using (user_id = auth.uid());
revoke all on subscriptions from anon, authenticated;
grant select on subscriptions to authenticated;

revoke all on stripe_events from anon, authenticated;

-- Opening a board by an edit link when the owner's plan has no editor seats left: the person
-- joins with a lower role instead. The app decides the cap; the old one-argument form stays.
create or replace function join_board_via_link(b uuid, cap text) returns text
language plpgsql security definer set search_path = public as $$
declare
  current text := board_role(b, auth.uid());
  via text;
begin
  if auth.uid() is null then return null; end if;
  if current is not null then return current; end if;
  if cap is not null and cap not in ('commenter', 'viewer') then raise exception 'bad role' using errcode = '22023'; end if;
  select link_role(link_access) into via from boards where id = b and deleted_at is null;
  if via is null then return null; end if;
  if via = 'editor' and cap is not null then via := cap; end if;
  insert into board_members (board_id, user_id, role) values (b, auth.uid(), via) on conflict do nothing;
  return via;
end;
$$;

revoke execute on function join_board_via_link(uuid, text) from public, anon;
grant execute on function join_board_via_link(uuid, text) to authenticated;
insert into schema_migrations (name) values ('0007_billing.sql');
commit;
