// Writes db/supabase-setup.sql: every migration in one transaction, plus the schema_migrations rows,
// for the Supabase SQL Editor when scripts/migrate.ts cannot reach the database. Usage: tsx scripts/bundle-migrations.ts
// With --from 0006 it writes db/supabase-update.sql instead: only migrations from that number on, for a database
// that already has the earlier ones.
import { promises as fs } from "node:fs";
import path from "node:path";

const dir = path.join(process.cwd(), "db", "migrations");
const fromArg = process.argv.indexOf("--from");
const from = fromArg > 0 ? process.argv[fromArg + 1] : null;
const files = (await fs.readdir(dir)).filter((f) => f.endsWith(".sql") && (!from || f >= from)).sort();
const out = from ? "supabase-update.sql" : "supabase-setup.sql";
const parts = [
  from
    ? `-- Migrations ${files[0]} to ${files.at(-1)} in one file, for a Supabase database that already has the earlier ones.`
    : "-- All migrations in one file, for pasting into the Supabase SQL Editor when `npm run db:migrate` cannot reach the database.",
  "-- Generated by scripts/bundle-migrations.ts; do not edit by hand. It records each migration, so a later `npm run db:migrate` skips them.",
  "-- Do not run it twice: the second run stops at the first table that already exists and changes nothing.",
  "begin;",
  "create table if not exists schema_migrations (name text primary key, applied_at timestamptz not null default now());",
];
for (const f of files) {
  parts.push(`\n-- ===== ${f} =====`, (await fs.readFile(path.join(dir, f), "utf8")).trim(), `insert into schema_migrations (name) values ('${f}');`);
}
parts.push("commit;\n");
await fs.writeFile(path.join(process.cwd(), "db", out), parts.join("\n"));
console.log(`db/${out}: ${files.length} migrations`);
