// The service worker's source, built as a string so it can carry the build version and the Russian
// offline page from lib/copy.ts. Served at /sw.js by app/sw.js/route.ts; registered only in production.
//
// What it keeps, per build version (older versions' caches are deleted on activate):
//   * /_next/static/*  hashed, public build files: cache first.
//   * /board/<id>      the board page a signed-in person opened (no query string, so never a guest link):
//                      network first, the cached copy only when the network fails.
// What it never touches: /api/* (tokens, images, billing), /auth/*, /login, server actions and other
// non-GET requests, RSC/data fetches, other origins. Signing in or out (/login) forgets every cached page.
import { t } from "../copy";

const escape = (s: string) => s.replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]!);

export function serviceWorkerSource(version: string): string {
  const offlineHtml = `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(t.offline.page)}</title>
<style>body{font:16px/1.5 system-ui,sans-serif;margin:0;min-height:100vh;display:flex;align-items:center;justify-content:center;padding:16px;text-align:center;color-scheme:light dark;color:CanvasText;background:Canvas}h1{font-size:20px;margin:0 0 8px}p{margin:0;opacity:.75;max-width:420px}</style></head>
<body><main><h1>${escape(t.offline.page)}</h1><p>${escape(t.offline.pageHint)}</p></main></body></html>`;

  return `// Generated by lib/offline/sw.ts. Version ${version}.
const VERSION = ${JSON.stringify(version)};
const STATIC = "mysl-static-" + VERSION;
const PAGES = "mysl-pages-" + VERSION;
const OFFLINE_HTML = ${JSON.stringify(offlineHtml)};
const BOARD = /^\\/board\\/[0-9a-f-]{36}$/;
const STATIC_PATH = /^\\/_next\\/static\\//;

self.addEventListener("install", () => self.skipWaiting());

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) if (key.startsWith("mysl-") && key !== STATIC && key !== PAGES) await caches.delete(key);
    await self.clients.claim();
  })());
});

const offline = () => new Response(OFFLINE_HTML, { status: 503, headers: { "Content-Type": "text/html; charset=utf-8", "Cache-Control": "no-store" } });

async function cacheFirst(request) {
  const cache = await caches.open(STATIC);
  const hit = await cache.match(request, { ignoreVary: true });
  if (hit) return hit;
  const res = await fetch(request);
  if (res.ok && res.type === "basic") cache.put(request, res.clone());
  return res;
}

// Only a full, successful page for a signed-in person is kept: a redirect (to sign in) drops the copy.
async function boardPage(request, path) {
  const cache = await caches.open(PAGES);
  try {
    const res = await fetch(request);
    if (res.ok && res.type === "basic" && !res.redirected) await cache.put(path, res.clone());
    else await cache.delete(path);
    return res;
  } catch (e) {
    return (await cache.match(path, { ignoreVary: true, ignoreSearch: true })) || offline();
  }
}

async function rememberPage(path, assets) {
  if (!BOARD.test(path)) return;
  const res = await fetch(path, { credentials: "same-origin", redirect: "manual" }).catch(() => null);
  if (res && res.ok && res.type === "basic" && !res.redirected) await (await caches.open(PAGES)).put(path, res);
  // Files the page loaded before this worker took control are not in the cache yet.
  const cache = await caches.open(STATIC);
  for (const a of assets || []) {
    let url;
    try { url = new URL(a, self.location.origin); } catch { continue; }
    if (url.origin !== self.location.origin || !STATIC_PATH.test(url.pathname)) continue;
    if (await cache.match(url.href, { ignoreVary: true })) continue;
    const r = await fetch(url.href).catch(() => null);
    if (r && r.ok && r.type === "basic") await cache.put(url.href, r);
  }
}

self.addEventListener("message", (event) => {
  if (event.origin && event.origin !== self.location.origin) return;
  const msg = event.data || {};
  if (msg.type === "remember-board" && typeof msg.path === "string") event.waitUntil(rememberPage(msg.path, Array.isArray(msg.assets) ? msg.assets.slice(0, 300) : []));
  if (msg.type === "forget-pages") event.waitUntil(caches.delete(PAGES));
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  const path = url.pathname;
  if (path.startsWith("/api/") || path.startsWith("/auth") || request.headers.get("RSC") || url.searchParams.has("_rsc")) return;
  if (STATIC_PATH.test(path)) return event.respondWith(cacheFirst(request));
  if (request.mode !== "navigate") return;
  if (path === "/login") {
    event.waitUntil(caches.delete(PAGES));
    return;
  }
  if (BOARD.test(path) && !url.search) return event.respondWith(boardPage(request, path));
  event.respondWith(fetch(request).catch(offline));
});
`;
}
